name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build the app
        working-directory: ./frontend
        run: npm run build

      - name: Start preview server
        working-directory: ./frontend
        run: nohup npm run preview &

      - name: Wait for server to be ready
        run: sleep 10

      - name: Run Cypress tests
        working-directory: ./frontend
        env:
          ELECTRON_DISABLE_GPU: 1
        run: npm run test:run
