name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Check Current Directory
        run: pwd && ls -la

      - name: Show package.json
        run: cat package.json

      - name: Install dependencies
        run: npm install

      - name: Check Available Scripts
        run: npm run

      - name: Check Installed Packages
        run: npm ls --depth=0

      - name: Build the app
        run: npm run build
