name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Start application
        run: npm start &
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          build: npm run build
          install: false
